# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from payment.grpc import payment_pb2 as payment_dot_grpc_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment/grpc/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/core.payment.PaymentController/Create',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/core.payment.PaymentController/Destroy',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/core.payment.PaymentController/List',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentListRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/core.payment.PaymentController/PartialUpdate',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentPartialUpdateRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/core.payment.PaymentController/Retrieve',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRetrieveRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/core.payment.PaymentController/Update',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
                _registered_method=True)


class PaymentControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentListRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentPartialUpdateRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRetrieveRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.payment.PaymentController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.payment.PaymentController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentController/Create',
            payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentController/Destroy',
            payment_dot_grpc_dot_payment__pb2.PaymentDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentController/List',
            payment_dot_grpc_dot_payment__pb2.PaymentListRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentController/PartialUpdate',
            payment_dot_grpc_dot_payment__pb2.PaymentPartialUpdateRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentController/Retrieve',
            payment_dot_grpc_dot_payment__pb2.PaymentRetrieveRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentController/Update',
            payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PaymentRequestControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/core.payment.PaymentRequestController/Create',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/core.payment.PaymentRequestController/Destroy',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/core.payment.PaymentRequestController/List',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestListRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestListResponse.FromString,
                _registered_method=True)
        self.PartialUpdate = channel.unary_unary(
                '/core.payment.PaymentRequestController/PartialUpdate',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestPartialUpdateRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/core.payment.PaymentRequestController/Retrieve',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestRetrieveRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/core.payment.PaymentRequestController/Update',
                request_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
                response_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
                _registered_method=True)


class PaymentRequestControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentRequestControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestListRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestPartialUpdateRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestRetrieveRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=payment_dot_grpc_dot_payment__pb2.PaymentRequest.FromString,
                    response_serializer=payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.payment.PaymentRequestController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.payment.PaymentRequestController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentRequestController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentRequestController/Create',
            payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentRequestController/Destroy',
            payment_dot_grpc_dot_payment__pb2.PaymentRequestDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentRequestController/List',
            payment_dot_grpc_dot_payment__pb2.PaymentRequestListRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentRequestListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentRequestController/PartialUpdate',
            payment_dot_grpc_dot_payment__pb2.PaymentRequestPartialUpdateRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentRequestController/Retrieve',
            payment_dot_grpc_dot_payment__pb2.PaymentRequestRetrieveRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.payment.PaymentRequestController/Update',
            payment_dot_grpc_dot_payment__pb2.PaymentRequest.SerializeToString,
            payment_dot_grpc_dot_payment__pb2.PaymentRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
